### ISSUE TITLE
[ Inacurate ] Execution Tactic:  T1059 From CTI Github | Enterprise Matrix

### ISSUE THREAD

**Issue by dfirence** [mitre/cti#100]
I just downloaded your Enterprise Matrix.

Is technique T1059 "REVOKED"? (Y/N)

Your matrix has it as revoked == true

But your website lists it as an active technique with Subtechniques.  This is affecting my statics and reporting for operational use of your matrix.

<br/>

## Revoked T1059

![image](https://user-images.githubusercontent.com/11415591/89734662-7c2d1680-da2b-11ea-9df5-1552ca29dfe2.png)

```
![image](https://user-images.githubusercontent.com/11415591/89734657-71728180-da2b-11ea-81c0-03a88460c60a.png)
```
<br/>
<br/>

## Active Subtechniques

![image](https://user-images.githubusercontent.com/11415591/89734693-a7b00100-da2b-11ea-915e-d5d4387e2955.png)

```
![image](https://user-images.githubusercontent.com/11415591/89734696-a979c480-da2b-11ea-8b08-dc2b73b95f71.png)
```

<br/>
<br/>

# Active in your website

![image](https://user-images.githubusercontent.com/11415591/89734719-cd3d0a80-da2b-11ea-9256-e0ecbd0a4b20.png)

```
![image](https://user-images.githubusercontent.com/11415591/89734721-d037fb00-da2b-11ea-8d03-669f0835a3ed.png)
```

**Comment by isaisabel** [comment]
I think there may be a bug in your parser -- [T1059 is not revoked according to our data](https://github.com/mitre/cti/blob/master/enterprise-attack/attack-pattern/attack-pattern--7385dfaf-6886-4229-9ecd-6fd678040830.json#L21). Is it possible that your parser is simply searching for the `revoked` field instead of checking that the field is also `True`?

**Comment by dfirence** [comment]
Ok, awesome, now I am good on T1059, applying the check on `revoked` key.  

**Can you standardize the enterprise.json** to have the revoked key across every technique?

This is a nightmare finding all of the inconsistencies.

<br/>

## After applying Check For Revoked Bool

![image](https://user-images.githubusercontent.com/11415591/89893550-8de6f900-dba6-11ea-8d32-9cde07452463.png)

```
![image](https://user-images.githubusercontent.com/11415591/89893553-8fb0bc80-dba6-11ea-994f-a6478bf1c6c9.png)
```

**Comment by isaisabel** [comment]
Hi @dfirence,

As noted in the USAGE document section [Removing revoked and deprecated objects](https://github.com/mitre/cti/blob/master/USAGE.md#removing-revoked-and-deprecated-objects), the default value for an absent boolean is `False` (and the default value for `revoked`, according to the STIX spec, [is False](https://docs.oasis-open.org/cti/stix/v2.0/csprd01/part1-stix-core/stix-v2.0-csprd01-part1-stix-core.html#_Toc476227328)). 

Due to the operation of our internal systems fields like `revoked` and `x_mitre_deprecated` only rarely show up explicitly in the `False` state — this occurs when the object in question was accidentally revoked or deprecated in our internal systems and then un-revoked/un-deprecated. Therefore these booleans usually only show up when they're `True`. I think for conciseness within our dataset we will probably continue omitting those fields when they are false.
