### ISSUE TITLE
[ Inacurate ] Privilege Escalation Tactic:  T1547 From CTI Github | Enterprise Matrix 

### ISSUE THREAD

**Issue by dfirence** [mitre/cti#101]
I just downloaded your Enterprise Matrix.

Why is your Github Matrix not showing T1547, **but** you have subtechniques assigned to it?

Your website shows it as active.

<br/>

# Missing T1547 From CTI Github Enterprise JSON

![image](https://user-images.githubusercontent.com/11415591/89735094-feb6d580-da2d-11ea-917a-d7106e4533b8.png)

```
![image](https://user-images.githubusercontent.com/11415591/89735096-00809900-da2e-11ea-848a-a4d6a29d1ca1.png)
```
<br/>
<br/>

## Active Subtechniques in CTI JSON

![image](https://user-images.githubusercontent.com/11415591/89735067-d929cc00-da2d-11ea-9baf-863d48e00c8a.png)

```
![image](https://user-images.githubusercontent.com/11415591/89734696-a979c480-da2b-11ea-8b08-dc2b73b95f71.png)
```

<br/>
<br/>

## Active Techniques in Website with Subtechniques

![image](https://user-images.githubusercontent.com/11415591/89735021-8bad5f00-da2d-11ea-96c6-4f9030c8f300.png)

```
![image](https://user-images.githubusercontent.com/11415591/89735021-8bad5f00-da2d-11ea-96c6-4f9030c8f300.png)
```

**Comment by isaisabel** [comment]
I'm not sure this is correct. Lines 2379 to 2449 of enterprise-attack.json show T1547 (AKA attack-pattern--1ecb2399-e8ba-4f6b-8ba7-5c27d49405cf), which can also be found [here](https://github.com/mitre/cti/blob/master/enterprise-attack/attack-pattern/attack-pattern--1ecb2399-e8ba-4f6b-8ba7-5c27d49405cf.json). In your first image, you appear to be searching for the ID using a lowercase t (`t1547` instead of `T1547`). I'm not sure what tool that is, but it could be causing the issue.

**Comment by dfirence** [comment]
Ah, ok I found the reason why I am not picking it up.

It is because the `enterprise.json` **does not have** the **datasources** key for **T1547**.  

However, you do assign datasources to the Subtechniques.



<br/>
<br/>

# **No Datasource Key**

![image](https://user-images.githubusercontent.com/11415591/89840380-1c736000-db3e-11ea-98e2-fc3655ad8d8b.png)


<br/>
<br/>


<br/>
<br/>

![image](https://user-images.githubusercontent.com/11415591/89840895-79234a80-db3f-11ea-9a04-59dac258c635.png)



<br/>
<br/>
<br/>


# After Including Items Without Assigned DataSources

![image](https://user-images.githubusercontent.com/11415591/89840246-c3a3c780-db3d-11ea-94de-d3fc4b66448a.png)


<br/>
<br/>
<br/>

Can you standardize this?

For example, look at T1021.

You have datasources assigned at both, the **technique** entry for T1021, and at the **subtechnique** entry for these.


<br/>
<br/>

![image](https://user-images.githubusercontent.com/11415591/89840571-91469a00-db3e-11ea-956a-ab71d5003df3.png)


```
![image](https://user-images.githubusercontent.com/11415591/89840574-93105d80-db3e-11ea-8115-b16e948c141d.png)
```

**Comment by isaisabel** [comment]
Hi @dfirence,

Data sources are not a required field for techniques within our dataset. Furthermore, techniques and their sub-techniques are only required to match in the following ways:
- Sub-technique ATT&CK IDs are a suffix of their parent IDs. For a given sub-technique ID Txxxx.yyy, Txxxx is the parent technique ID and yyy is the sub-technique ID. Sub-techniques have unique STIX IDs.
- Sub-techniques have the same tactics as their parent technique.
- Sub-techniques have a subset of their parent technique's platforms.

Sub-techniques do not necessarily match their parent technique in terms of data sources, group/software/mitigation mappings, etc.

[The STIX spec states that lists cannot be empty](https://docs.oasis-open.org/cti/stix/v2.0/csprd01/part1-stix-core/stix-v2.0-csprd01-part1-stix-core.html#_Toc476227318):
> [...] every list instance *MUST* have at least one value
> [...] Empty lists are prohibited in STIX and *MUST NOT* be used as a substitute for omitting the property if it is optional. If the property is required, the list MUST be present and MUST have at least one value.

Therefore fields like `x_mitre_data_sources` are omitted when we have no defined values (instead of leaving an empty array) since to do otherwise would violate the STIX spec.
