### ISSUE TITLE
Deprecated controls appears in non-deprecated relationships

### ISSUE THREAD

**Issue by slimbentami** [mitre/cti#120]
Hello,
one example:
The control `course-of-action--4320b080-9ae9-4541-9b8b-bcd0961dbbbd` has `x_mitre_deprecated = TRUE`.
The relationship `relationship--47316750-4ca7-4ea3-b72c-9d7c7d895e3a` which involves that control is however not deprecated (nor revoked).
Is this to be expected?
Thank you

**Comment by isaisabel** [comment]
Hi @slimbentami,

ATT&CK does not typically revoke or deprecate relationships. We consider a relationship revoked or deprecated if one of the objects it is attached to is revoked or deprecated. So this is expected behavior.

This design should however be documented better in our USAGE document, so I'll keep this issue open to reflect that we have improvements to make there.

**Comment by slimbentami** [comment]
Hi @isaisabel, many thanks.
