### ISSUE TITLE
Why Sub-techniques are mapped to Tactics?

### ISSUE THREAD

**Issue by Radu3000** [mitre/cti#146]
Sub-Techniques are already mapped to Techniques and Techniques to Tactics, right?  It would be redundant to map Sub-techniques to Tactics, right?  Unless there is something different ... or?

**Comment by isaisabel** [comment]
Hi @Radu3000,

As noted in the USAGE document, sub-techniques always have the same tactics as their parent technique. We keep the tactic mapping on sub-techniques since it makes it easier to filter that way, e.g a user could find all techniques and sub-techniques under Execution with a single query, instead of having to find techniques in Execution, then find the sub-techniques of those techniques. 

It's a quality of life thing in the data model, just like the `x_mitre_is_subtechnque` field which is also duplicative since you could just look for the relevant relationship. But `x_mitre_is_subtechnque` again is easier to use with filters than finding specific relationships.

It's also a matter of consistency. Sub-techniques are a _type_ of technique (attack-pattern), and their data model isn't really treated any differently than normal techniques. This ensures code written for techniques also works for sub-techniques (e.g you can [determine the tactics of a sub-technique in isolation](https://github.com/mitre/cti/blob/master/enterprise-attack/attack-pattern/attack-pattern--0af0ca99-357d-4ba1-805f-674fdfb7bef9.json#L52-L57), without needing extra queries not required for techniques).
