### ISSUE TITLE
Should technique -> tactic be mapped as relationship?

### ISSUE THREAD

**Issue by FergusNelson** [mitre/cti#152]
It took me a while to figure out that relationship between a tactic and the techniques within it are mapped as the `x_mitre_shortname` of the tactic in the `kill_chain_phases.phase_name`  

Is there any reason not to make this relationship more clear by adding in the first class `relationship` objects into the stix export? I think adding this would make it more explicit. 

Secondary question - Is there a conept of a primary tactic? Techniques can belong to multiple tactics, for example, [Replication Through Removable Media](https://attack.mitre.org/techniques/T1091/) belongs to both Lateral Movement and Initial Access, but when I view this technique on the MITRE ATT&CK website it is highlighhted on the LHS as being part of Initial access. Does this indicate that initial access is the primary tactic for this technique, or just happens to be the first tactic ordered by kill phase .

Thanks

**Comment by isaisabel** [comment]
Were we designing STIX, or our representation of the dataset in STIX, from the ground up, I would probably agree that tactics should be relationships. However, I don't think tactics should be a relationship at present for two reasons:
- `kill_chain_phases` is a stock STIX functionality and we strive to use stock STIX functionalities whenever possible. `x-mitre-tactic` is a custom STIX type, so while we could add relationships to it, that would be duplicative to `kill_chain_phases`.
- A lot of existing infrastructure within the ATT&CK team, and externally with our users, is reliant on the current implementation of tactics through `kill_chain_phases`. We can't remove that field at this time, and we generally try not to have duplicative fields/representations to simplify maintenance.

Historically we used kill_chain_phases because `x-mitre-tactic` objects did not exist in the initial STIX representation(s) of the dataset. So tactics were entirely stored in `kill_chain_phases` because there was no object to create a relationship with.

---

For the second question, no there is no primary tactic. In the ATT&CK website (I believe) it is always the first tactic in the list which the technique appears within that is expanded by default. So the expansion of a tactic in the sidebar is not particularly meaningful, it's just a quirk of the UI.
