### ISSUE TITLE
How to get ICS Assets programmatically?

### ISSUE THREAD

**Issue by MaurizioCasciano** [mitre/cti#161]
I need to get all the assets belonging to the ICS domain, as displaied at https://collaborate.mitre.org/attackics/index.php/All_Assets
Is there some reference in the ICS Matrix?
Here the corresponding question on Stack Overflow https://stackoverflow.com/questions/67536762/mitre-attck-ics-how-to-get-all-assets-from-taxii-server

**Comment by chrisante7** [comment]
Hi @MaurizioCasciano! The creators of the ATTACK-Python-Client made an exploratory ICS ATT&CK notebook that you can check out here: https://mybinder.org/v2/gh/OTRF/ATTACK-Python-Client/master?filepath=notebooks/ICS_ATTACK_Exploration.ipynb

Working off that notebook, you can retrieve all the assets like so:
![image](https://user-images.githubusercontent.com/70962962/118525309-07e77800-b70d-11eb-8b13-6ed6a1b01881.png)

ICS assets are represented as <code>x_mitre_platforms</code> STIX objects, so hopefully the example above helps. Let me know if you have any questions. Thanks!

**Comment by MaurizioCasciano** [comment]
Thanks @chrisante7, this way we can get the names of the ICS assets.
How to get the entire asset object, with description, notes and levels?
I tried by filtering on the type `x_mitre_platforms` without success.

```
    def getAssets(self):
        assets = self.source.query([
            Filter("type", "=", "x-mitre-platforms")
        ])

        return assets
```

**Comment by chrisante7** [comment]
@MaurizioCasciano Unfortunately assets are not their own dedicated objects compared to something like <code>attack-pattern</code> or <code>intrusion-set</code>. Those STIX objects are assigned to a <code>type</code>, but assets in the ICS STIX are represented as <code>x_mitre_platforms</code>, which similar to Enterprise and Mobile, would not return a dedicated STIX object. So feedback for your code block would be that you wouldn't be able to query <code>x_mitre_platforms</code> as a <code>type</code>.

ATT&CK ICS is unique from Enterprise and Mobile in that the matrix is still hosted on a wiki page, rather than a dedicated ATT&CK website. The wiki provides flexibility to the ICS ATT&CK team to represent data that isn't found in the other domains e.g. things like Assets, Levels, etc. We were able to represent unique data fields like Assets as an existing STIX object (<code>x_mitre_platforms</code>), but for others like Levels that cannot be easily mapped to an existing STIX object, there is no STIX representation.

**Comment by MaurizioCasciano** [comment]
I understood, thanks for the explanation @chrisante7.
So, basically, we should wait/suggest the STIX project to consider adding new object types in order to have a mapping with all the objects in ATT&CK?

**Comment by isaisabel** [comment]
Hi @MaurizioCasciano,

In theory we can add a custom STIX type for assets, e.g `x-mitre-asset` or something to that effect. We already do this with matrices (`x-mitre-matrix`), tactics (`x-mitre-tactic`), and the upcoming datasource refactor (`x-mitre-data-source, #130). It's just difficult to add that new type with our internal infrastructure and we decided to use the platforms field since it's a pretty close match and would be supported by existing tools such as the ATT&CK Navigator.

So essentially it's likely we'll make the improvement to give assets a full object sometime in the future, but we don't need to wait for the STIX project to add a type for it to do so.

**Comment by isaisabel** [comment]
Data sources (#130) is a pretty good model for what this refactor look like since it's taking an existing `string[]` field and turning it into full objects.

**Comment by CyberDaedalus00** [comment]
@MaurizioCasciano - you might want to reach out to the CTI community as there has been recent discussion about defining a STIX Asset object.  While I don't expect this to go through the typical standards process, at least you could engage with the community that is discussing it.

**Comment by isaisabel** [comment]
Discussion of future improvements aside I think the question has been answered, so I'm closing the issue.

**Comment by MaurizioCasciano** [comment]
@CyberDaedalus00  @isaisabel  How/where can I reach out the CTI community?

**Comment by isaisabel** [comment]
STIX is maintained by oasis-open, so their site should have links. Probably [their contribute page](https://oasis-open.github.io/cti-documentation/contribute.html) would be a good place to start.
