### ISSUE TITLE
Mitre Enterprise Relationships that contain revoked/deprecated elements, have revoked=False

### ISSUE THREAD

**Issue by SteliosZ** [mitre/cti#174]
Hello. 

Context: I want to populate a database with the Mitre Enterprise information, queried from the official Mitre Taxii server. Before that, the deprecated/revoked items are removed.

When trying to correlate the relationships with the saved objects that I have in my database (Groups, Software, Tactics etc), I noticed that some relationships that contain revoked elements, such as:"relationship--433a0302-dce9-4ee5-b13f-b5d3f18e3836" for example, have their "revoked" value equal to False.
(revoked element within this relationship: "intrusion-set--dc5e2999-ca1a-47d4-8d12-a6984b138a1b")

After that, I noticed that the number of the relationships that I am getting before and after the removal of the deprecated/revoked elements, is exactly the same.

Shouldn't the revoked field be marked as True inside relationships too, or am I missing something from the documentation ?

Thank in advance for your time :)

**Comment by isaisabel** [comment]
Hi @SteliosZ,

This is mentioned briefly in our USAGE document under the section of revoked/deprecated relationships:
> Unlike other objects in the dataset, relationships cannot be revoked or deprecated. Relationships are considered deprecated/revoked if one of the objects it is attached to is revoked or deprecated.

In the STIX 2.0 dataset on this repository (mirrored on our TAXII server) relationships are never deprecated nor revoked. With subsequent releases irrelevant relationships are simply removed from the dataset entirely instead of being marked consistently with the other object types. Also, when an object they are attached to is revoked/deprecated, the relationship is generally not removed or marked in any way. You basically have to infer that they are irrelevant by checking their attached objects for revocation/deprecation markings. This is due to a limitation in the tool used to build the STIX 2.0 dataset.

However, in our [STIX 2.1 representation of the dataset](https://github.com/mitre-attack/attack-stix-data) we do properly deprecate or revoke relationships instead of deleting them. You can use the data on that repo if deprecated/revoked relationships are important to your use case since it's the same exact data (albeit with some formatting improvements). 

I'm not sure if we will propagate that change over to this repository in the future, but if we did it would most likely only apply to the subsequent releases of ATT&CK and not previous releases (that is to say we wouldn't re-add deleted relationships as deprecated to ATT&CK v6, v7... etc). Unfortunately we do not currently have a TAXII server for our STIX 2.1 dataset, but we do hope to set one up eventually.

Hope this helped!

**Comment by SteliosZ** [comment]
> 
> 
> Hi @SteliosZ,
> 
> This is mentioned briefly in our USAGE document under the section of revoked/deprecated relationships:
> 
> > Unlike other objects in the dataset, relationships cannot be revoked or deprecated. Relationships are considered deprecated/revoked if one of the objects it is attached to is revoked or deprecated.
> 
> In the STIX 2.0 dataset on this repository (mirrored on our TAXII server) relationships are never deprecated nor revoked. With subsequent releases irrelevant relationships are simply removed from the dataset entirely instead of being marked consistently with the other object types. Also, when an object they are attached to is revoked/deprecated, the relationship is generally not removed or marked in any way. You basically have to infer that they are irrelevant by checking their attached objects for revocation/deprecation markings. This is due to a limitation in the tool used to build the STIX 2.0 dataset.
> 
> However, in our [STIX 2.1 representation of the dataset](https://github.com/mitre-attack/attack-stix-data) we do properly deprecate or revoke relationships instead of deleting them. You can use the data on that repo if deprecated/revoked relationships are important to your use case since it's the same exact data (albeit with some formatting improvements).
> 
> I'm not sure if we will propagate that change over to this repository in the future, but if we did it would most likely only apply to the subsequent releases of ATT&CK and not previous releases (that is to say we wouldn't re-add deleted relationships as deprecated to ATT&CK v6, v7... etc). Unfortunately we do not currently have a TAXII server for our STIX 2.1 dataset, but we do hope to set one up eventually.
> 
> Hope this helped!

Thanks for the quick reply.

My main goal is to use your TAXII server. (I've setup a custom TAXII client to grep the 2.0 dataset). 
Hope that you will eventually set up one with the 2.1 version of the dataset, as you said.

In any case, thank you for the quote from the documentation, which I didn't notice,
and for the recommendation of the 2.1 dataset repo, mainly because I didn't know it existed. :)
