### ISSUE TITLE
how to save the data to db and we can migrate it to myself 

### ISSUE THREAD

**Issue by xx-zhang** [mitre/cti#178]
i want to create my new Att&CK, but is there some covinient way to contibute it. and then we scan save the data to mysql or es for updating .

**Comment by isaisabel** [comment]
Hi @xx-zhang,

If your intention is to modify the ATT&CK knowledge base for your own means, we recommend you check out the [ATT&CK Workbench](https://github.com/center-for-threat-informed-defense/attack-workbench-frontend/) project. ATT&CK Workbench allows you to extend existing ATT&CK objects (E.g techniques, groups, software, and the mappings between them) or create new ones in a local copy of the ATT&CK knowledge base. 

ATT&CK Workbench is backed by a mongo database where the data is saved which is to my knowledge the only open-source tool for putting ATT&CK STIX data in a database. Utilities are included for importing and exporting data from this database so that it's easy to get started. Workbench also includes utilities for staying up to date with subsequent updates to the knowledge base when they're released.

Check out the repository or announcement blog post for more details:
- GitHub repo: https://github.com/center-for-threat-informed-defense/attack-workbench-frontend/
- Blog post: https://medium.com/mitre-engenuity/att-ck-workbench-a-tool-for-extending-att-ck-e1718cbfe0ef

If you want to contribute to the official ATT&CK knowledge base (e.g this repository), please see our contributing page for more information: https://attack.mitre.org/resources/contribute/
