### ISSUE TITLE
Platform set to "None" in ICS

### ISSUE THREAD

**Issue by pljoel** [mitre/cti#195]
Hi MITRE,

Thanks for maintaining this awesome repo!
&nbsp;

I noticed that some ICS ATT&CK techniques have the platform list items set to "None" rather than being empty. Eg.:
`"x_mitre_platforms": [ "None" ]` instead of `"x_mitre_platforms": []`.

Is having `"None"` in the list a bug or expected?
It would make handling the data easier if the `x_mitre_platforms` list was empty, although the ATT&CK website wouldn't show the platform field anymore unless we change its logic ([ATT&CK website HTML technique logic](https://github.com/mitre-attack/attack-website/blob/master/modules/techniques/templates/technique.html#L200-L209)).
&nbsp;

See ICS techniques with `x_mitre_platforms` with `"None"` item:
1. [T0887](https://github.com/mitre/cti/blob/master/ics-attack/attack-pattern/attack-pattern--0fe075d5-beac-4d02-b93e-0f874997db72.json#L7-L9)
2. [T0831](https://github.com/mitre/cti/blob/master/ics-attack/attack-pattern/attack-pattern--1af9e3fd-2bcc-414d-adbd-fe3b95c02ca1.json#L7-L9)
3. [T0837](https://github.com/mitre/cti/blob/master/ics-attack/attack-pattern/attack-pattern--2bb4d762-bf4a-4bc3-9318-15cc6a354163.json#L7-L9)
4. [T0815](https://github.com/mitre/cti/blob/master/ics-attack/attack-pattern/attack-pattern--56ddc820-6cfb-407f-850b-52c035d123ac.json#L7-L9)
5. [T0880](https://github.com/mitre/cti/blob/master/ics-attack/attack-pattern/attack-pattern--5fa00fdd-4a55-4191-94a0-564181d7fec2.json#L7-L9)
6. [T0828](https://github.com/mitre/cti/blob/master/ics-attack/attack-pattern/attack-pattern--63b6942d-8359-4506-bfb3-cf87aa8120ee.json#L7-L9)
7. [T0817](https://github.com/mitre/cti/blob/master/ics-attack/attack-pattern/attack-pattern--7830cfcf-b268-4ac0-a69e-73c6affbae9a.json#L7-L9)
8. [T0879](https://github.com/mitre/cti/blob/master/ics-attack/attack-pattern/attack-pattern--83ebd22f-b401-4d59-8219-2294172cf916.json#L7-L9)
9. [T0827](https://github.com/mitre/cti/blob/master/ics-attack/attack-pattern/attack-pattern--a81696ef-c106-482c-8f80-59c30f2569fb.json#L7-L9)
10. [T0826](https://github.com/mitre/cti/blob/master/ics-attack/attack-pattern/attack-pattern--b5b9bacb-97f2-4249-b804-47fd44de1f95.json#L7-L9)
11. [T0882](https://github.com/mitre/cti/blob/master/ics-attack/attack-pattern/attack-pattern--b7e13ee8-182c-4f19-92a4-a88d7d855d54.json#L7-L9)
12. [T0884](https://github.com/mitre/cti/blob/master/ics-attack/attack-pattern/attack-pattern--d67adac8-e3b9-44f9-9e6d-6c2a7d69dbe4.json#L7-L9)
13. [T0813](https://github.com/mitre/cti/blob/master/ics-attack/attack-pattern/attack-pattern--e33c7ecc-5a38-497f-beb2-a9a2049a4c20.json#L7-L9)

**Comment by chrisante7** [comment]
Hi @pljoel, 

Having `"None"` in the `"x_mitre_platforms"` field is expected behavior. Like you mentioned, if the platform field was empty, then both the website and ATT&CK navigator wouldn't show the technique.

The platforms tag for ICS techniques is a bit different from traditional Enterprise techniques. Before the ICS matrix was transitioned to the main ATT&CK website, the platforms on the ICS wiki were referred to as [Assets](https://collaborate.mitre.org/attackics/index.php/All_Assets). We didn't have a STIX representation for assets, so we associated assets with `x_mitre_platforms`. 

To your answer your question more specifically though, the ICS techniques you listed don't have platforms/assets that we can point back to from a defender's perspective vs. a technique like [T0840](https://attack.mitre.org/techniques/T0840/), which has `Human-Machine Interface` since that behavior typically happens on HMIs. 

Hope this helps!

**Comment by pljoel** [comment]
Thanks for your answer @chrisante7 !
I will update my scripts and filter out the `"None"` items knowing that.

Thanks again!
