### ISSUE TITLE
Bug: All MITRE ATT&CK ICS Techniques have "x_mitre_platforms": [ "None" ]

### ISSUE THREAD

**Issue by MaurizioCasciano** [mitre/cti#223]
Hi @jondricek @ElJocko @isaisabel, I have found that the platforms of all MITRE ATT&CK ICS Techniques have not been added.
All ICS Techniques have "x_mitre_platforms": [ "None" ]

E.g. https://github.com/mitre/cti/blob/master/ics-attack/ics-attack.json#L8311

![image](https://github.com/mitre/cti/assets/12021064/f3578485-1c15-477a-84f3-295a42dd6c0b)

The same happens also on the website https://attack.mitre.org/techniques/T0889/
where the associated assets
![image](https://github.com/mitre/cti/assets/12021064/8df427b6-a8c9-4d81-b358-7c686c132273)

have Embedded platform:
![image](https://github.com/mitre/cti/assets/12021064/d21e5107-a741-48f8-8d5b-1df323e9f922)
![image](https://github.com/mitre/cti/assets/12021064/8dcc2b3a-93b6-465d-9451-684dca59cfe8)

**Comment by MaurizioCasciano** [comment]
Equal to what found for STIX 2.1 dataset repository https://github.com/mitre-attack/attack-stix-data/issues/46

**Comment by jondricek** [comment]
@MaurizioCasciano the reason for this is that the ICS domain had been using the `x_mitre_platforms` field as a placeholder for what ultimately was the Asset STIX object which was introduced in the v14 release on Oct. 31 this year. More information about Assets can be found in the [ATT&CK v14 blog post](https://medium.com/mitre-attack/attack-v14-fa473603f86b). At that time, the Assets were removed from the `x_mitre_platforms` field and intentionally replaced with `[ "None" ]` because the STIX specification doesn't allow empty arrays and at present we want to keep that field in every Technique object even if there is no value to make parsing more straightforward, even though the value of `"None"` might be confusing.

This is the same answer to https://github.com/mitre-attack/attack-stix-data/issues/46
