### ISSUE TITLE
Deprecated Attack Patterns Revoked

### ISSUE THREAD

**Issue by LiamSennitt** [mitre/cti#24]
I noticed that attack patterns that have been deprecated, for example PRE-T1146 (`cti/pre-attack/attack-pattern/attack-pattern--489a7797-01c3-4706-8cd1-ec56a9db3adc.json`), aren't marked as revoked?

**Comment by jburns12** [comment]
Hi @LiamSennitt - thanks for bringing this up. 

For each of the deprecated techniques, we added an x_mitre_deprecated attribute and set its value to "true" instead of using the revoked property. This is the case for all of the techniques that still have a page on our website, such as this one https://attack.mitre.org/pre-attack/index.php/Technique/PRE-T1158.

We are reserving the revoked property for techniques/software/groups that are replaced or combined with others techniques/software/groups. An example of that is how MONSOON was combined with Patchwork on the latest content update.

Here's the MONSOON object:
https://github.com/mitre/cti/blob/master/enterprise-attack/intrusion-set/intrusion-set--9559ecaf-2e75-48a7-aee8-9974020bc772.json

And here's the relationship expressing how it was revoked by Patchwork:
https://github.com/mitre/cti/blob/master/enterprise-attack/relationship/relationship--3680408d-e56e-4d68-a74d-2678093ed53f.json

Hopefully this is helpful, but let us know if you have any other questions or concerns!

**Comment by LiamSennitt** [comment]
That makes sense, missed the `x_mitre_deprecated` thanks for clarifying.
