### ISSUE TITLE
redundant aliases

### ISSUE THREAD

**Issue by VladimirAlexiev** [mitre/cti#30]
`malware--123bd7b3-675c-4b1a-8482-c55782b20e2b` has these (in Turtle not JSON notation, but you get the point):
```
stix:name                 "BUBBLEWRAP" ;        
mitre:aliases             "Backdoor.APT.FakeWinHTTPHelper" , "BUBBLEWRAP" .
```
The second `alias` is redundant because it's the same as `name`.

BTW where can I post STIX bugs? I think these should be moved to [Common Properties](http://docs.oasis-open.org/cti/stix/v2.0/cs01/part1-stix-core/stix-v2.0-cs01-part1-stix-core.html#_Toc496709274): `name aliases description`

**Comment by johnwunder** [comment]
As a non-member of the working group developing STIX, the best way to make comments is via the cti-comment mailing list, here: https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=cti#feedback

Once you make that comment, as a member of the TC I can then go ahead and add an issue to our STIX tracker. The reason you need to send it to that mailing list is because there's an IPR disclosure involved.

**Comment by johnwunder** [comment]
In regards to `BUBBLEWRAP` being duplicated in both name and aliases, that was an intentional decision...we wanted to give it a clear name of course, but didn't want to imply that the name wasn't just another alias that it was known by. This mirrors how we do it on the website as well.

If you're OK with submitting the STIX bug to the STIX issue tracker I'll go ahead and close this issue in a couple days.
