### ISSUE TITLE
Create a test enterprise attack.json  file

### ISSUE THREAD

**Issue by Daniel-Li-Anomali** [mitre/cti#32]
Can someone create an enterprise attack .json file with only a couple of threats? It would make it alot easier to create unit tests.

**Comment by jburns12** [comment]
Hi @Daniel-Li-Anomali - I know it's been a bit since you posted this, but hopefully you found a solution. If not, one suggestion would be locally merging some of the individual intrusion-sets into a single bundle in the same format as enterprise-attack.json or deleting some of the groups from the current enterprise-attack.json locally and ingest that file in your tooling.
