### ISSUE TITLE
[Question] TAXII Server Usage - Pagination and added_after

### ISSUE THREAD

**Issue by m-harptq** [mitre/cti#40]
Hello there,

We're implementing ingestion of MITRE ATT&CK data within our product via TAXII 2.0 and I've run into a few issues on the get objects endpoints.

As per the TAXII 2.0 [specification](https://docs.google.com/document/d/1Jv9ICjUNZrOnwUXtenB1QcnBLO35RnjQcJLsa1mGSkI/pub#h.tvfy419udzxi), one should be able to do the following on a `<api-root>/collections/<id>/objects/` endpoint:
* Paginate response objects via a `Range: items X-Y` header
* Filter via an `added_after` query string parameter given a timestamp value in the form of `YYYY-MM-DDTHH:mm:ss.[s+]Z`

Using the [Enterprise Attack](https://cti-taxii.mitre.org/stix/collections/95ecc380-afe9-11e4-9b6c-751b66dd541e/objects), [Pre-Attack](https://cti-taxii.mitre.org/stix/collections/062767bd-02d2-4b72-84ba-56caef0f8658/objects), or [Mobile Attack](https://cti-taxii.mitre.org/stix/collections/2f669986-b40b-4423-b720-4396ca6a462b/objects) endpoints I cannot get either of these options to work for the life of me. Are these options actually supported by the MITRE TAXII Server?

Thanks!

**Comment by emmanvg** [comment]
Hi @m-harptq, thanks for raising this question. The MITRE TAXII 2.0 Server does support paginated requests, but does not implement support for the `added_after` parameter. For awareness the second example under Section 3.4.3 has a typo\error when the document was written. The request should be made following the [RFC7233](http://www.rfc-editor.org/info/rfc7233) format. Perhaps a better example of the syntax can be found here [Range | MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range). If you have further questions let me know. Otherwise, I think we can close this issue. Hope this helps!

**Comment by m-harptq** [comment]
@emmanvg Thanks so much, of course it was a simple typo! Feel free to close!

**Comment by emmanvg** [comment]
To give you a broader context behind this, currently the TAXII server hosts the latest objects as they are published into this repository. Thus, having the `added_after` functionality does not make a lot of sense since it is not holding all versions of a given object (you would get the same response regardless of the parameter being available/supported). Though, this change in the future.

In addition, if you follow the technical specification development. In TAXII 2.1 Pagination was removed  altogether because problems were found by members\implementers of the specification. It may be re-introduced on an future version if a solution is designed by the group. I would recommend that you follow and engage in those efforts if you are interested in advancing this technology!
