### ISSUE TITLE
Duplicates in course of actions

### ISSUE THREAD

**Issue by andreamargheri** [mitre/cti#57]
Course of actions for Capec and Enterprise ATT&CK have SDOs with same description only differing for id and name. Could the duplicates be removed? 

Capec has 207 duplicates, here filter to identify them

`c = fs_capec.query([Filter('id', '=', 'course-of-action--288326b3-896e-463c-b6ff-5dc65f4e77c0')])
print(len(fs_capec.query(Filter('description', '=', c[0].description)))
`

**Comment by isaisabel** [comment]
@rpiazza any thoughts on this?

**Comment by rpiazza** [comment]
Hi @andreamargheri,

Sorry it took so long to respond.  @isaisabel is doing a cleanup of open issues, and noticed your issue.

If you are still interested in this issue, I have a few questions.  

You claim that capec courses-of-action has 207 duplicates, and give a filter query.  I'm not sure what this query supposed to show - it appears you are looking for COAs that have the same description as course-of-action--288326b3-896e-463c-b6ff-5dc65f4e77c0.  I just did a grep of the COA directory (grep "All user" *) - which returned 7 different COAs.  However, the descriptions were actually unique -since they all contained additional different text.

The capec2stix script will not create a duplicate COA if the description is exactly the same as an already existing one.  If this is buggy - it needs to be corrected.  If you could help me determine what you are seeing, that would be great!

**Comment by andreamargheri** [comment]
HI @rpiazza, 

The COA are actually different as they may contain different values (like ids), but the field description seems to be repeated. Am I wrong?

**Comment by rpiazza** [comment]
Can you give an example?  

Also, make sure you are using the current content from mitre-cti, because it has changed since this issue was first opened.

**Comment by andreamargheri** [comment]
Ok, yes you are right. I tested the code I used and it does not show any repetition.
