### ISSUE TITLE
Some mitigation url are broken

### ISSUE THREAD

**Issue by gtsafeB** [mitre/cti#60]
Hi,
There some course-of-action(mitigation) that has an incorrect reference link.
for example:
https://attack.mitre.org/mitigations/T1012

And there are some more.

**Comment by isaisabel** [comment]
Hi @gtsafeB,

The recent [July 2019 ATT&CK update](https://attack.mitre.org/resources/updates/updates-july-2019/index.html) comprised of a major change to how we represent enterprise mitigations. To facilitate this change we deprecated all of the old mitigations (with IDs starting with T) in favor of new mitigations (with IDs starting with M).

On the old website, Enterprise mitigations were unique to each technique (they had a 1:1 relationship with techniques). They were found on the technique pages as you can see [in this preserved page from an older version of the website](https://attack.mitre.org/previous/april2019/techniques/T1012/).

Now that mitigitations have been moved to their own pages, the old deprecated mitigations don’t actually have pages on the website anymore which is why their reference links don’t work. Deprecated objects are no longer supported, however we keep them available for historical purposes.
