### ISSUE TITLE
Some Mitigations point to a deprecated web page

### ISSUE THREAD

**Issue by HamptonJ** [mitre/cti#68]
Some Course of Action Objects have external reference urls of "https://attack.mitre.org/mitigations/T****" and all of these that I have checked have returned a 404 error. I believe the correct urls are now similar to this "https://attack.mitre.org/mitigations/M1041"

**Comment by isaisabel** [comment]
Hi @HamptonJ,

The URLs you're pointing out are on objects which are marked as deprecated (they have the `x_mitre_deprecated` field — [see here for an example](https://github.com/mitre/cti/blob/master/enterprise-attack/course-of-action/course-of-action--073cc04d-ac46-4f5a-85d7-83a91ecd6a19.json#L25)). Therefore the fact that their web pages are no longer present on the site is the expected behavior.

[A more detailed explanation can be found on my response to a duplicate issue here](https://github.com/mitre/cti/issues/60#issuecomment-517267745).

**Comment by HamptonJ** [comment]
I can't believe I didn't notice this! Thanks for your response.
