### ISSUE TITLE
Naming convention for Beta MITRE ATT&CK sub-techniques

### ISSUE THREAD

**Issue by nconder** [mitre/cti#75]
To stick with the naming conventions in the [new beta sub-techniques](https://mitre-attack.github.io/attack-navigator/beta/enterprise/) the 'root' technique should end with ".000" for example T1566.000.

**Comment by isaisabel** [comment]
Hi @nconder,

The different formatting of technique IDs and sub-technique IDs was carefully planned to communicate the hierarchy of the data. The "root" or "parent" technique is a level above its sub-techniques, which is why the sub-technique IDs are suffixes of their parent's ID. You can read more about the hierarchy of techniques and sub-techniques in our [FAQ](https://attack.mitre.org/beta/resources/faq/).

The ID scheme is also used for the path of techniques on the ATT&CK website, e.g `https://attack.mitre.org/beta/techniques/T1548/` is the parent URL and `https://attack.mitre.org/beta/techniques/T1548/001/` is the URL of the first sub-technique.
