### ISSUE TITLE
Windows defender false positive

### ISSUE THREAD

**Issue by VakarisZ** [mitre/cti#76]
Hi. I've basically have the same issue as #67. We use ATT&CK data as part of our project, and the problems are that it makes the project look as a malicious software and it gets import error once defender removes the file. Is there a way to hide/change that particular line of code or somehow avoid detection? Or should we do it on our end and it's beyond the scope of this project? 
![image](https://user-images.githubusercontent.com/36815064/79541333-4e921b00-8092-11ea-9dd4-57a43bccd0c8.png)

**Comment by isaisabel** [comment]
Hi @VakarisZ,

We're attempting to change the portion of the STIX which windows defender is getting false-positives on so that it won't appear as malicious. Our current strategy is to replace some of the characters with similar-looking Unicode equivalents. Specifically, we're replacing the dollar sign `$` with a [fullwidth dollar sign](https://unicode-table.com/en/FF04/) `＄`, and the semicolon `;` with a [greek question mark](https://unicode-table.com/en/037E/) `;`.

Here's the patched attack-pattern. Can you check whether your antivirus gives you problem with it? We'd like to verify that our change is actually effective for you before proceeding to make the change official.

[web_shell.json.zip](https://github.com/mitre/cti/files/4493043/web_shell.json.zip)

**Comment by VakarisZ** [comment]
No, these particular files doesn't produce false positives.

**Comment by isaisabel** [comment]
Hi @VakarisZ,

After some consideration we decided against the unicode-replacement method. Adding unicode replacements to the data could cause problems if people were copy/pasting the example into defensive tools. Therefore we've reached out to Microsoft to try to get the false positive fixed so that we won't have to resort to an imperfect method like unicode replacements.
