### ISSUE TITLE
"aliases" and "x_mitre_aliases" - why two?

### ISSUE THREAD

**Issue by Radu3000** [mitre/cti#87]
I understand that "aliases" items are for groups (i.e. intrusion-sets) and "x_mitre_aliases" are for malwares.  But why two items with similar name to accomplish the same thing?  

Second "alias" does not say explicitly for groups and "x_mitre_aliases" doesn't say explicitly for malwares.

**Comment by isaisabel** [comment]
Hi @Radu3000,

`aliases` is a part of the STIX spec only for [intrusion-sets](https://docs.oasis-open.org/cti/stix/v2.0/csprd01/part2-stix-objects/stix-v2.0-csprd01-part2-stix-objects.html#_Toc476230941), but not for [malware](https://docs.oasis-open.org/cti/stix/v2.0/csprd01/part2-stix-objects/stix-v2.0-csprd01-part2-stix-objects.html#_Toc476230945) or [tools](https://docs.oasis-open.org/cti/stix/v2.0/csprd01/part2-stix-objects/stix-v2.0-csprd01-part2-stix-objects.html#_Toc476230961). 

Therefore we have to use a custom property for adding aliases to software (`malware` and `tool`) objects, and according to the [customizing STIX](https://docs.oasis-open.org/cti/stix/v2.0/csprd01/part1-stix-core/stix-v2.0-csprd01-part1-stix-core.html#_Toc476227365) guidance custom properties must be prefixed with `x_` followed by a source identifier. Thus for malware and tool objects we must use `x_mitre_aliases` instead of `aliases`.

Regarding your second question, this has been addressed in our upcoming rewrite of the usage documentation (see #86).

**Comment by Radu3000** [comment]
Thank you Isabel - that helps!
