### ISSUE TITLE
Model in Attack Design and Philosophy document not matching the model in json on gitbhub

### ISSUE THREAD

**Issue by Radu3000** [mitre/cti#94]
On page 17 of https://attack.mitre.org/docs/ATTACK_Design_and_Philosophy_March_2020.pdf I see a more elaborate model for relationships than the one in json at https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json

No "Prevents" or "Accomplishes" relationships in json.  (Course of Action replaced with Mitigation?)

- Why is that?  Am not using the right json?

Thanks,
Radu

**Comment by isaisabel** [comment]
Hi @Radu3000,

That diagram is not representative of the literal STIX data, but rather how the ATT&CK catalog can be interpreted. Prevents can be seen as synonymous to `mitigates` (the `relationship_type` used in that context), and likewise a software `uses` [sub-]techniques instead of "implementing" them.

`Accomplishes` is not a relationship, but rather is expressed in the `kill_chain_phases` field on techniques.
